# Generated by Django 4.1 on 2022-08-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Cart',
        ),
    ]
